//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia_Sistemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionInstructore
    {
        public int IdAsignacion { get; set; }
        public Nullable<int> IdInstructor { get; set; }
        public Nullable<int> IdProgramacion { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual Instructore Instructore { get; set; }
        public virtual ProgramacionesCurso ProgramacionesCurso { get; set; }
    }
}
