//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia_Sistemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionInstructore
    {
        public int IdAsignacion { get; set; }
        public Nullable<int> IdInstructor { get; set; }
        public Nullable<int> IdProgramacion { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual Instructore Instructore { get; set; }
        public virtual ProgramacionesCurso ProgramacionesCurso { get; set; }
    }
}
