//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia_Sistemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacione
    {
        public int IdCalificacion { get; set; }
        public Nullable<int> IdInscripcion { get; set; }
        public decimal Nota { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Inscripcione Inscripcione { get; set; }
    }
}
