//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia_Sistemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int IdCompra { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdEquipo { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int Cantidad { get; set; }
        public decimal CostoUnitario { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
