//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia_Sistemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int IdCompra { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdEquipo { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int Cantidad { get; set; }
        public decimal CostoUnitario { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
