//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia_Sistemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioEquipos
    {
        public int IdInventario { get; set; }
        public Nullable<int> IdEquipo { get; set; }
        public Nullable<int> IdSede { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
