//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia_Sistemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioEquipos
    {
        public int IdInventario { get; set; }
        public Nullable<int> IdEquipo { get; set; }
        public Nullable<int> IdSede { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
