//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia_Sistemas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Academia_SistemasEntities : DbContext
    {
        public Academia_SistemasEntities()
            : base("name=Academia_SistemasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsignacionInstructore> AsignacionInstructores { get; set; }
        public virtual DbSet<Calificacione> Calificaciones { get; set; }
        public virtual DbSet<CategoriasCurso> CategoriasCursos { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Inscripcione> Inscripciones { get; set; }
        public virtual DbSet<Instructore> Instructores { get; set; }
        public virtual DbSet<InventarioEquipos> InventarioEquipos { get; set; }
        public virtual DbSet<Modalidade> Modalidades { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<Perfile> Perfiles { get; set; }
        public virtual DbSet<ProgramacionesCurso> ProgramacionesCursos { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<Sede> Sedes { get; set; }
        public virtual DbSet<Usuario_Perfil> Usuario_Perfil { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
