//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia_Sistemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int IdCPago { get; set; }
        public Nullable<int> IdInscripcion { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Monto { get; set; }
        public string MetodoPago { get; set; }
    
        public virtual Inscripcione Inscripcione { get; set; }
    }
}
